- name: Create directory
  file:
    path: "~/example_directory"
    state: directory
    mode: '0755'

- name: Create file and add text
  copy:
    dest: "~/example_directory/example_file.txt"
    content: |
      This is some text in the file.
    mode: '0644'

- name: Add a line to the file
  lineinfile:
    path: "~/example_directory/example_file.txt"
    line: 'This is another line added to the file.'
    insertafter: EOF
